services:
  - type: web
    name: flask-projeto5
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URI
        value: "postgresql://<usuario>:<senha>@<host>:<porta>/<database>?sslmode=require&channel_binding=require"
      - key: MONGODB_URI
        value: "mongodb://<usuario>:<senha>@<host>:<porta>/<database>"
