services:
  - type: web
    name: flask-projeto5
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: banco-1
          property: connectionString
      - key: MONGODB_URI
        value: "mongodb://<usuario>:<senha>@<host>:<porta>/<database>"

databases:
  - name: banco-1
    plan: free
    databaseName: banco 1
    user: projeto5
